version: '3'

tasks:
  default:
    cmds:
      - task: test

  setup:
    preconditions:
      - test ! -z $(command -v pre-commit)
    cmds:
      - pre-commit install -f

  test:
    preconditions:
      - test ! -z $(command -v bats)
      - test ! -z $(command -v podman)
    cmds:
      - ./scripts/test.sh

  package:
    preconditions:
      - test ! -z $(command -v tar)
    cmds:
      - rm -rf dist
      - mkdir -p dist
      - tar zcvf dist/ignity.tar.gz -C src/ .
